export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',

  // ✨ Added prompts below
  'A futuristic AI robot painting a portrait of itself, concept art',
  'A fantasy castle floating above the clouds at sunset',
  'A cyberpunk samurai meditating under neon cherry blossoms',
  'A steampunk city powered by flying whales, digital art',
  'A cozy coffee shop inside a spaceship orbiting Mars',
  'A realistic photo of a dragon resting on top of a skyscraper in Dubai',
  'A cat dressed as an ancient Egyptian pharaoh, realistic detail',
  'A glowing jellyfish city underwater, 3D concept design',
  'A digital painting of a warrior riding a giant butterfly through the clouds',
  'An astronaut discovering a glowing ancient temple on the moon',
  'A realistic portrait of a humanoid alien blending into human society',
  'A futuristic train flying across neon-lit mountains at night',
  'A mystical forest filled with holographic animals, fantasy art',
  'A robot chef preparing sushi in a Tokyo restaurant, cinematic lighting',
  'A post-apocalyptic city reclaimed by nature, matte painting style',
  'A floating island marketplace with airships and glowing crystals',
  'A woman made of galaxies, cosmic surrealism',
  'A neon cyberpunk street with rain reflections and flying cars',
  'A cute robot watering digital plants in a VR garden',
  'A surreal photo of a piano melting into the ocean at sunrise',
  'A time traveler stepping out of a portal into 1920s Paris, cinematic art',
  'A futuristic sports car powered by plasma energy racing through a tunnel',
  'A retro robot walking a dog made of light, synthwave style',
  'A city skyline built entirely of glass and light, minimalist design',
  'A phoenix reborn from data streams, AI concept art',
];
